# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('cover_format', models.CharField(choices=[('PB', 'paperback'), ('HC', 'hardcover')], max_length=2)),
                ('num_pages', models.PositiveIntegerField()),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('year_publish', models.DateField(blank=True, null=True)),
                ('edition', models.PositiveIntegerField(blank=True, null=True)),
                ('ISBN10', models.CharField(max_length=10, unique=True)),
                ('ISBN13', models.CharField(max_length=13, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('feedback', models.CharField(blank=True, max_length=1000)),
                ('order_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_copies', models.PositiveIntegerField()),
                ('order_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('entry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booklist.Book')),
                ('num_copies', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.Book'),
        ),
        migrations.AddField(
            model_name='rating',
            name='feedback_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to='booklist.User'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='booklist.User'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.Book'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.Book'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.User'),
        ),
    ]
